init.{
  set start cost 0-> set nodes cost infinity -> add start to queue
}

init -> while queue has members

while queue has members.{
  get connected-> for each connected

  for each connected.{
    cost = connection + restricted -> has been visited?
    has been visited? -> cost rn smaller? -> save new cost :yes
    save new cost -> continue
    cost rn smaller? -> continue : no

    has been visited?-> add to queue with priority : no
    add to queue with priority -> save new cost
  }
}





